In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
!pip install --upgrade pip

   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
    --------------------------------------- 0.0/1.8 MB 330.3 kB/s eta 0:00:06
   - -------------------------------------- 0.1/1.8 MB 550.5 kB/s eta 0:00:04
   ---- ----------------------------------- 0.2/1.8 MB 1.1 MB/s eta 0:00:02
   ----------- ---------------------------- 0.5/1.8 MB 2.7 MB/s eta 0:00:01
   ------------------------------------- -- 1.6/1.8 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 6.6 MB/s eta 0:00:00


ERROR: To modify pip, please run the following command:
E:\Python\my_env\Scripts\python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

1D Array: [1 2 3 4 5]


In [4]:
print(type(arr1))  # Output: <class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [5]:
print("Array Shape:", arr1.shape)

Array Shape: (5,)


In [6]:
arr2=np.array([1,2,3,4,5,6]).reshape(2,3)

In [7]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# creating 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
# Idenity matrix
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
# NUmpy Vectorized Operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", a + b)

# Element-wise Subtraction
print("Subtraction:", a - b)

# Element-wise Multiplication
print("Multiplication:", a * b)

# Element-wise Division
print("Division:", a / b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [14]:
# Universal Functions
arr = np.array([1, 4, 9, 16])

# Square root
print("Square Root:", np.sqrt(arr))

# Exponential
print("Exponential:", np.exp(arr))

# Sine
print("Sine:", np.sin(arr))

# natural logarithm
print("Natural Logarithm:", np.log(arr))

Square Root: [1. 2. 3. 4.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]
Natural Logarithm: [0.         1.38629436 2.19722458 2.77258872]


In [17]:
# array Slicing and Indexing
arr = np.array([[10, 20, 30, 40, 50],[60,70,80,90,100],[110,120,130,140,150]])
print("Original Array:\n", arr)

Original Array:
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]


In [18]:
# Accessing elements
print("Element at (0,0):", arr[0, 0])
print("Element at (1,2):", arr[1, 2])
print("Element at (2,4):", arr[2, 4])

Element at (0,0): 10
Element at (1,2): 80
Element at (2,4): 150


In [19]:
arr[2:]

array([[110, 120, 130, 140, 150]])

In [20]:
arr[1:,]

array([[ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [21]:
arr[1:, 2:]

array([[ 80,  90, 100],
       [130, 140, 150]])

In [22]:
# Modifying elements
arr[0, 0] = 99

In [23]:
arr

array([[ 99,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [25]:
arr[1:, 2:] = 88

In [27]:
arr

array([[ 99,  20,  30,  40,  50],
       [ 60,  70,  88,  88,  88],
       [110, 120,  88,  88,  88]])

In [28]:
# Statistical Operations
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [30]:
# mean
print("Mean:", np.mean(data))
# median
print("Median:", np.median(data))
# standard deviation
print("Standard Deviation:", np.std(data))
# Normalization
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print("Normalized Data:\n", normalized_data)

Mean: 5.0
Median: 5.0
Standard Deviation: 2.581988897471611
Normalized Data:
 [[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


In [31]:
# variance
print("Variance:", np.var(data))

Variance: 6.666666666666667


In [32]:
# Logical Operations
arr = np.array([10, 20, 30, 40, 50])

# Elements greater than 25
print("Elements greater than 25:", arr > 25)

# Elements less than or equal to 30
print("Elements less than or equal to 30:", arr <= 30)

Elements greater than 25: [False False  True  True  True]
Elements less than or equal to 30: [ True  True  True False False]
